### ISSUE TITLE
Config expiration always reset to 12 * time.Hour

### ISSUE THREAD

**Issue by fuadarradhi** [gofiber/session#17]
I need to set no expiration session, but config always reset it to 12 * time.Hour,

for now, i just remove this line
https://github.com/gofiber/session/blob/f685507f406b832543f23eed7410d6026581812c/session.go#L85-L87

**Comment by Fenny** [comment]
Having an expiration is good practice, but you could also use `1 * time.Millisecond`

**Comment by fuadarradhi** [comment]
in documentation :
0 means no expiry (24 years),

maybe you need to update this

**Comment by Fenny** [comment]
You are correct! I missed that part, PR's are welcome 🙏

**Comment by Fenny** [comment]
This package is deprecated, we wrote our own session middleware and released it within fiber core.
See https://github.com/gofiber/fiber/tree/master/middleware/session for more information.
