### ISSUE TITLE
Questions for session implementation

### ISSUE THREAD

**Issue by 979156** [gofiber/session#2]
Hi Fenny, I want to ask you some questions about session.
1. Will you wrap fasthttp/session and follow the pattern it's using?
2. Is this package going to be used as middleware?
 
I implemented some part of code wrapping that and tested using Postgres and built Save and Get methods to use. If it's same way you are going, I will make PR and wish this helps your hardworking on fiber packages.

**Comment by Fenny** [comment]
@979156 sorry for the late reply, @thomasvvugt and I are currently writing a new session middleware.
This should be released soon.
