### ISSUE TITLE
Support for SetSessionID()

### ISSUE THREAD

**Issue by circledata** [gofiber/session#26]
Hello,

Are you able to enable SetSessionID() like it is in github.com/fasthttp/session?

**Comment by Fenny** [comment]
Hi! We are working on an internal session middleware that has support for setting a custom ID 👍

**Comment by nextstuff** [comment]
Awesome. Thank you!

**Comment by Fenny** [comment]
This package is deprecated, we wrote our own session middleware and released it within fiber core.
See https://github.com/gofiber/fiber/tree/master/middleware/session for more information.
