### ISSUE TITLE
How to save reference to mongo client in session?

### ISSUE THREAD

**Issue by swilso793** [gofiber/session#52]
How would i go about saving a reference to the mongo connection in essence caching the connection and not having to make the call every time? 

```
client, err := getMongoDbConnection(credentials)
store.Set("mongoRef", client)
err = store.Save()
fmt.Println(store.Get("mongoRef")
fmt.Println(err)

>>>>

<nil>
msgp: type "mongo.Client" not supported at D/2/Value
```

**Comment by Fenny** [comment]
This package is deprecated, we wrote our own session middleware and released it within fiber core.
See https://github.com/gofiber/fiber/tree/master/middleware/session for more information.
