### ISSUE TITLE
store.Destroy not real working for v2.0.2

### ISSUE THREAD

**Issue by GordonWu** [gofiber/session#59]
Dear Team:

First all According to old version gofiber/session(v1.2.5) "Destroy" function is working fine. But when we upgrade to v2.0.2, "Destroy" function has been change, and if we still follow Example from README.md "Destroy" function will not working to "delete storage + cookie".

In our research, we find out the issue maybe is "Destroy" function itself has not been "Reset" dict data any more. So when we call "Save" function the dict data has been store back. 

So we are very confused about it, are we missing something? Or this issue will be fix?

B.R & Tks.
Gordon

**Comment by Fenny** [comment]
We are currently re-writing the session middleware from scratch so we can port it into fiber core.
It should be finished this week, and this repo will be deprecated. 

I leave this issue open for now, apologies.

**Comment by GordonWu** [comment]
Dear Team:

Thanks for the reply.
We are looking forward to the next update.

B.R & Tks.
Gordon
