### ISSUE TITLE
Session data seems to not be saved between requests

### ISSUE THREAD

**Issue by edimoldovan** [gofiber/session#72]
Hi,

It seems my session is not being saved, question is am I doing this right? I am not entirely sure so here's a little more context.
I am implementing a simple session-based login like this:
``` 
storage := sqlite3.New()
store := session.New(session.Config{
  Storage: storage,
})
```

then I save it
``` 
sess.Set("email", "email@email.com")
defer sess.Save()
```

and then I try to read the value:
``` 
email := sess.Get("email")
log.Println(email)
log.Println(sess.Keys())
```

So my first question is: am I doing it right?

**Comment by ReneWerner87** [comment]
if you want to save and read the session in the middlewares then try it without "defer" at the sess.Save call

defer is executed only at the end of the run, but our middlewares are nested by the ctx.Next call, which sometimes causes problems there

**Comment by edimoldovan** [comment]
I tried it like that. So far, with the defer I could read the saved session in the route handler where I was receiving the email I want to save. But without defer it isn't saved there either.

**Comment by ReneWerner87** [comment]
need more code with the connections and the handlers to help you

**Comment by edimoldovan** [comment]
@ReneWerner87 I can add you to the repo itself, there's no secret in there. It's just a learning repo, basically a blog engine I would like to use and make it open-source later when it's sort of functional.

**Comment by ReneWerner87** [comment]
sure, just share the link

**Comment by edimoldovan** [comment]
I added you to the repo, you should receive an invitation. Here's the repo link [repo](https://github.com/edimoldovan/relee.se)

**Comment by ReneWerner87** [comment]
please update the whole project from fiber v1 to v2
https://github.com/edimoldovan/relee.se/blob/main/go.mod#L10

**Comment by ReneWerner87** [comment]
have simply reduced the setup to the important points

```go
package main

import (
    "log"

    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/fiber/v2/middleware/session"
)

func main() {
	app := fiber.New()
	// storage := sqlite3.New()
	store := session.New(session.Config{
		// Storage:      storage,
		//CookieDomain: "relee.se",
	})

	app.Get("/", func(c *fiber.Ctx) error {

		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}

		email := sess.Get("email")
		log.Println(email)
		log.Println(sess.Keys())

		return c.SendString("index")
	})

	app.Get("/update", func(c *fiber.Ctx) error {
		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}

		sess.Set("email", "email@email.com")
		defer sess.Save()

		log.Println(sess.Get("email"))
		log.Println(sess.Keys())

		return c.SendString("update")
	})

	log.Fatal(app.Listen(":3000"))
}
```

![image](https://user-images.githubusercontent.com/7063188/168789709-f062aaf4-5f2c-420a-9a76-6366c83c1f5c.png)
![image](https://user-images.githubusercontent.com/7063188/168789742-461f84a4-7533-408c-9ddb-145853e49b6b.png)
and it is working

please check if the cookie is there after the 
https://github.com/edimoldovan/relee.se/blob/577d076cb94e33f47107873342f0389525d5739c/router/router.go#L101
call

and hopefully you run everything on the domain "relee.se" -> otherwise don´t wonder that the cookie is not present and not accessable

https://github.com/edimoldovan/relee.se/blob/577d076cb94e33f47107873342f0389525d5739c/router/router.go#L60

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/168790616-85704073-b179-4a36-b0fa-a33cd71f5c81.png)
![image](https://user-images.githubusercontent.com/7063188/168790643-2333b6db-a787-4ed8-b2f6-a6848002c461.png)

its just a GET request not a POST request.
i think you miss the method
![image](https://user-images.githubusercontent.com/7063188/168790821-df3e88ac-9f7e-4b68-bfbf-f1db78edb219.png)

**Comment by edimoldovan** [comment]
As I assumed, it was my mistake. I ran the entire thing on the wrong domain. Thank you for your time. Happy to buy you a drink, a coffee or return the favour somehow. Please let me know.

Closing the issue.
