### ISSUE TITLE
Session Destroy and Regenerate not working

### ISSUE THREAD

**Issue by DanielAtwood** [gofiber/session#9]
I can't seem to get sessions to be destroyed or regenerated. I've tried both memcache and mysql but `store.Destroy()` and `store.Regenerate()` aren't doing anything that I can tell. Am I doing something wrong?

```
Mac OSX        : 10.15.4
Fiber          : v1.12.0
Fiber Session  : v1.2.1
```

**Comment by Fenny** [comment]
Could you provide a example code to re-produce?

**Comment by DanielAtwood** [comment]
Here's the flow:
`/`: <nil>
`/`: Logged in
`/`: true
`/logout`: Logged out
`/`: true Expected `<nil>`
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/session"
)

func main() {
	app := fiber.New()
	sessions = session.New(session.Config{Secure: true})

	app.Get("/", func(c *fiber.Ctx) {
		store := sessions.Get(c)
		defer store.Save()

		c.Send(store.Get("valid"))
	})

	app.Get("/login", func(c *fiber.Ctx) {
		store := sessions.Get(c)
		defer store.Save()
		store.Set("valid", true)
		c.Send("Logged in! ", store.ID())
	})

	app.Get("/logout", func(c *fiber.Ctx) {
		store := sessions.Get(c)
		defer store.Save()
		store.Destroy()
		c.Send("Logged out!")
	})

	app.Listen(3000)
}
```

**Comment by Fenny** [comment]
Thank you, I can see that `Destroy` does not work correctly. We will investigate and keep you updated.

**Comment by DanielAtwood** [comment]
Awesome thanks!

**Comment by thomasvvugt** [comment]
Hi @DanielAtwood
I have tested this locally as well and it seems that `store.Destroy()` does indeed not remove entries from the session provider.
I do think this is a problem the underlying [fasthttp/session](github.com/gofiber/session).

@Fenny Maybe it's worth to do some more testing and creating an issue there?

**Comment by DanielAtwood** [comment]
I ran this locally and all of the functions worked with `mysql` and `memory`. [fasthttp/session](https://github.com/fasthttp/session/) seems to work just fine.

[fasthttp/session examples](https://github.com/fasthttp/session/tree/master/_examples)

**Comment by Fenny** [comment]
@DanielAtwood thanks for the report, fixed in https://github.com/gofiber/session/releases/tag/v1.2.2 ❤️
